'use strict';
const {hash, assert} = require('./primitives.cjs');
const timestamps = 'created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP';
const ddl = [
 `CREATE TABLE IF NOT EXISTS commerce_settlement_business_contexts (id VARCHAR(36) PRIMARY KEY,biz_type VARCHAR(24) NOT NULL,source_order_system VARCHAR(32) NOT NULL,biz_order_no VARCHAR(100) NOT NULL,payment_mode VARCHAR(24) NOT NULL,execution_scope VARCHAR(32) NOT NULL,party_id VARCHAR(64) NOT NULL,currency CHAR(3) NULL,snapshot JSON NOT NULL,${timestamps},UNIQUE KEY uk_context(biz_type,source_order_system,biz_order_no),KEY party_idx(party_id,biz_type)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_party_bindings (id VARCHAR(36) PRIMARY KEY,source_domain VARCHAR(32) NOT NULL,source_entity_type VARCHAR(32) NOT NULL,source_entity_id VARCHAR(64) NOT NULL,party_id VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'draft',created_by VARCHAR(64) NOT NULL,reviewed_by VARCHAR(64) NULL,${timestamps},UNIQUE KEY uk_party_binding(source_domain,source_entity_type,source_entity_id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_profiles (id VARCHAR(36) PRIMARY KEY,party_id VARCHAR(64) NOT NULL,biz_type VARCHAR(24) NOT NULL,payment_mode VARCHAR(24) NOT NULL,version INT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'draft',created_by VARCHAR(64) NOT NULL,reviewed_by VARCHAR(64) NULL,snapshot JSON NOT NULL,${timestamps},UNIQUE KEY uk_profile(party_id,biz_type,payment_mode,version)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_payment_accounts (id VARCHAR(36) PRIMARY KEY,party_id VARCHAR(64) NOT NULL,provider VARCHAR(32) NOT NULL,environment VARCHAR(24) NOT NULL,merchant_no VARCHAR(128) NOT NULL,contract_no VARCHAR(128) NULL,currency CHAR(3) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'draft',version INT NOT NULL DEFAULT 1,capabilities JSON NOT NULL,created_by VARCHAR(64) NOT NULL,reviewed_by VARCHAR(64) NULL,${timestamps},KEY party_idx(party_id,status)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_funding_sources (id VARCHAR(36) PRIMARY KEY,context_id VARCHAR(36) NOT NULL,payment_id VARCHAR(64) NULL,source_type VARCHAR(32) NOT NULL,provider VARCHAR(32) NOT NULL,environment VARCHAR(24) NOT NULL,currency CHAR(3) NOT NULL,account_id VARCHAR(36) NOT NULL,contract_no VARCHAR(128) NOT NULL,received_minor BIGINT NOT NULL,reserved_minor BIGINT NOT NULL DEFAULT 0,consumed_minor BIGINT NOT NULL DEFAULT 0,returned_minor BIGINT NOT NULL DEFAULT 0,status VARCHAR(24) NOT NULL,evidence JSON NOT NULL,${timestamps},UNIQUE KEY uk_source(provider,environment,source_type,payment_id),KEY context_idx(context_id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_units (id VARCHAR(36) PRIMARY KEY,context_id VARCHAR(36) NOT NULL,unit_key VARCHAR(100) NOT NULL,recognition_id VARCHAR(100) NOT NULL,status VARCHAR(24) NOT NULL,basis_minor BIGINT NOT NULL,source_id VARCHAR(36) NULL,rule_snapshot JSON NOT NULL,calculation JSON NOT NULL,evidence JSON NOT NULL,confirmed_at DATETIME NOT NULL,${timestamps},UNIQUE KEY uk_unit(context_id,unit_key),UNIQUE KEY uk_recognition(context_id,recognition_id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_policies (id VARCHAR(36) PRIMARY KEY,party_id VARCHAR(64) NULL,biz_type VARCHAR(24) NOT NULL,payment_mode VARCHAR(24) NOT NULL,version INT NOT NULL DEFAULT 1,priority INT NOT NULL DEFAULT 0,mode VARCHAR(16) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'draft',conditions JSON NOT NULL,nodes JSON NOT NULL,created_by VARCHAR(64) NOT NULL,reviewed_by VARCHAR(64) NULL,${timestamps},KEY match_idx(biz_type,payment_mode,status,priority)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_adjustments (id VARCHAR(36) PRIMARY KEY,item_id BIGINT NOT NULL,item_revision INT NOT NULL,kind VARCHAR(32) NOT NULL,before_snapshot JSON NOT NULL,after_snapshot JSON NOT NULL,reason VARCHAR(1000) NOT NULL,evidence JSON NULL,status VARCHAR(24) NOT NULL,created_by VARCHAR(64) NOT NULL,reviewed_by VARCHAR(64) NULL,${timestamps},KEY item_idx(item_id,status)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_approval_instances (id VARCHAR(36) PRIMARY KEY,item_id BIGINT NOT NULL,item_revision INT NOT NULL,policy_id VARCHAR(36) NULL,purpose VARCHAR(32) NOT NULL DEFAULT 'FUND_EXECUTION',status VARCHAR(24) NOT NULL,nodes JSON NOT NULL,current_node INT NOT NULL DEFAULT 0,created_by VARCHAR(64) NOT NULL,snapshot JSON NOT NULL,${timestamps},KEY item_idx(item_id,status)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_approval_actions (id VARCHAR(36) PRIMARY KEY,instance_id VARCHAR(36) NOT NULL,node_index INT NOT NULL,account_id VARCHAR(64) NOT NULL,action VARCHAR(16) NOT NULL,note VARCHAR(1000) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uk_action(instance_id,node_index,account_id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_authorizations (id VARCHAR(36) PRIMARY KEY,item_id BIGINT NOT NULL,item_revision INT NOT NULL,mode VARCHAR(24) NOT NULL,purpose VARCHAR(32) NOT NULL,hash CHAR(64) NOT NULL,snapshot JSON NOT NULL,status VARCHAR(24) NOT NULL,expires_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY item_idx(item_id,item_revision,status)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY,actor_id VARCHAR(64) NOT NULL,operation VARCHAR(100) NOT NULL,request_key VARCHAR(128) NOT NULL,payload_hash CHAR(64) NOT NULL,result JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uk_request(actor_id,operation,request_key)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_audit (id BIGINT AUTO_INCREMENT PRIMARY KEY,actor_id VARCHAR(64) NOT NULL,action VARCHAR(100) NOT NULL,resource_id VARCHAR(128) NOT NULL,payload JSON NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY resource_idx(resource_id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_ledger_events (id VARCHAR(36) PRIMARY KEY,event_key VARCHAR(255) NOT NULL UNIQUE,context_id VARCHAR(36) NULL,payload_hash CHAR(64) NOT NULL,payload JSON NOT NULL,posted_at DATETIME NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY context_idx(context_id,posted_at)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS commerce_settlement_fulfillment (id VARCHAR(36) PRIMARY KEY,context_id VARCHAR(36) NOT NULL,order_no VARCHAR(100) NOT NULL,account_id VARCHAR(64) NOT NULL,event_kind VARCHAR(32) NOT NULL,evidence JSON NOT NULL,confirmed_at DATETIME NOT NULL,UNIQUE KEY uk_fulfillment(context_id,event_kind)) ENGINE=InnoDB`,
];
const itemColumns = {
 context_id:'VARCHAR(36) NULL',unit_id:'VARCHAR(36) NULL',component_key:'VARCHAR(64) NULL',beneficiary_party_id:'VARCHAR(64) NULL',account_id:'VARCHAR(36) NULL',source_id:'VARCHAR(36) NULL',
 revision:'INT NOT NULL DEFAULT 1',original_payable_minor:'BIGINT NULL',planned_minor:'BIGINT NULL',discharged_minor:'BIGINT NOT NULL DEFAULT 0',reserved_minor:'BIGINT NOT NULL DEFAULT 0',cancelled_minor:'BIGINT NOT NULL DEFAULT 0',offset_minor:'BIGINT NOT NULL DEFAULT 0',authorization_id:'VARCHAR(36) NULL',not_before_at:'DATETIME NULL',hold_reason:'VARCHAR(255) NULL',updated_at:'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
};
async function column(c,table,name,definition) {
 const [exists] = await c.execute('SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?',[table,name]);
 if(!exists.length) await c.query(`ALTER TABLE \`${table}\` ADD COLUMN \`${name}\` ${definition}`);
}
async function migrate(c) {
 // Old 004/005 definitions remain byte-for-byte immutable. This is a new, restartable migration.
 await c.query('CREATE TABLE IF NOT EXISTS commerce_migrations(version VARCHAR(64) PRIMARY KEY,checksum CHAR(64) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)');
 const checksum=hash({ddl,itemColumns,version:1}), version='007_unified_settlement';
 const [[prior]]=await c.execute('SELECT checksum FROM commerce_migrations WHERE version=?',[version]);
 if(prior) { assert(prior.checksum===checksum,'共享结算迁移校验失败',500); return; }
 await require('../../commerce/settlement.cjs').migrate(c);
 for(const sql of ddl) await c.query(sql);
 for(const [name,type] of Object.entries(itemColumns)) await column(c,'commerce_settlement_items',name,type);
 await c.query('ALTER TABLE commerce_settlement_items MODIFY line_kind VARCHAR(32) NOT NULL, MODIFY batch_id BIGINT NULL, MODIFY redemption_id VARCHAR(40) NULL, MODIFY coupon_id VARCHAR(40) NULL, MODIFY order_id VARCHAR(40) NULL, MODIFY merchant_id BIGINT NULL, MODIFY city_id BIGINT NULL');
 const [[index]]=await c.execute("SELECT 1 ok FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='commerce_settlement_items' AND INDEX_NAME='uk_shared_component' LIMIT 1");
 if(!index) await c.query('ALTER TABLE commerce_settlement_items ADD UNIQUE KEY uk_shared_component(unit_id,component_key,beneficiary_party_id), ADD KEY shared_context_idx(context_id,status)');
 await column(c,'commerce_ledger_entries','event_id','VARCHAR(36) NULL');
 await column(c,'commerce_ledger_entries','context_id','VARCHAR(36) NULL');
 await c.execute('INSERT INTO commerce_migrations(version,checksum) VALUES(?,?)',[version,checksum]);
}
module.exports={ddl,itemColumns,migrate,column};
