'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {applyPlan,hash}=require('../../commerce/initialization.cjs');
async function run({pool,service,actors,check,sku,store,merchant}){
 const plan=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../docs/verification/newliving-commerce-initialization/plan.json'),'utf8'));
 let first;
 await check('Initialization creates an auditable linked draft graph without human approvals',async()=>{first=await applyPlan(pool,plan);assert.equal(first.created.length,plan.records.length);for(const entry of first.created){const record=await service.entity(pool,entry.kind,entry.id);assert.equal(record.status,'draft');assert.equal(record.created_by,0);assert.equal(record.published_version,null);assert.equal(record.reviewed_by,null);if(entry.kind==='packages')for(const item of record.payload.items){assert((await service.entity(pool,'skus',item.sku_id)).id);assert((await service.entity(pool,'rules',item.rule_id)).id);}}});
 await check('Repeated initialization preserves edits and creates no duplicate records',async()=>{const chosen=first.created.find(v=>v.kind==='merchants');await pool.execute('UPDATE commerce_merchants SET name=? WHERE id=?',['初始化后人工编辑',chosen.id]);const second=await applyPlan(pool,plan);assert.equal(second.created.length,0);assert.equal(second.existing.length,plan.records.length);assert.equal((await service.entity(pool,'merchants',chosen.id)).name,'初始化后人工编辑');});
 await check('Unconfirmed prices remain null; external services are never zero-price coupons',async()=>{const initial=first.created.filter(v=>v.kind==='skus');for(const r of initial){const e=await service.entity(pool,'skus',r.id);assert.equal(e.payload.supply_minor,null);assert(!/insurance-|finance-|recycle-|telecom-portability|community-groupbuy|asset-custody/.test(e.payload.initialization.source.slug||''));}const plans=first.created.filter(v=>v.kind==='plans');assert.equal(plans.length,1);const member=await service.entity(pool,'plans',plans[0].id);assert.equal(member.payload.name,'新居住会员');assert.equal(member.payload.price_minor,99900);assert.equal(member.payload.valid_days,365);const gift=await service.entity(pool,'packages',member.payload.package_id);assert.equal(gift.payload.items.length,5);assert.equal(gift.payload.price_minor,99900);});
 await check('Incomplete initialized configurations cannot be submitted or appear in public catalogue',async()=>{for(const r of first.created)await assert.rejects(()=>service.transition(actors.writer,'commerce.admin.write',r.kind,r.id,{version:1,action:'submit'}));const publicIds=new Set((await service.catalog()).map(r=>r.kind+':'+r.id));for(const r of first.created)assert(!publicIds.has(r.kind+':'+r.id));});
 await check('Initializer rolls back the entire batch when a dependency is missing',async()=>{const [before]=await pool.query('SELECT COUNT(*) n FROM commerce_merchants');const broken={...plan,batch:plan.batch+'-rollback',records:JSON.parse(JSON.stringify(plan.records))};broken.records[1].refs.merchant_id='missing-dependency';await assert.rejects(()=>applyPlan(pool,broken),/Unresolved seed dependency/);const [after]=await pool.query('SELECT COUNT(*) n FROM commerce_merchants');assert.equal(before[0].n,after[0].n);});
 await check('Unbound supplier draft can be completed once; established scope cannot move',async()=>{const pending=first.created.find(v=>v.key==='sku:membership:cleaning');const payload={...sku.payload,merchant_id:merchant.id,store_id:store.id,name:'会员专供服务'};const updated=await service.save(actors.writer,'commerce.admin.write','skus',pending.id,{version:1,payload});assert.equal(updated.merchant_id,merchant.id);assert.equal(updated.vendor_id,merchant.vendor_id);assert(updated.payload.initialization);const own=first.created.find(v=>v.kind==='merchants');await assert.rejects(()=>service.save(actors.writer,'commerce.admin.write','merchants',own.id,{version:1,payload:{name:'不允许换主体',vendor_id:2,city_id:1,contract_ref:'contract',contact:'contact',phone:'000000',description:'描述'}}),/不能变更/);});
 const output=path.resolve(__dirname,'../../docs/verification/newliving-commerce-initialization');fs.writeFileSync(path.join(output,'test-results.json'),JSON.stringify({at:new Date().toISOString(),plan_sha256:hash(plan),tests:6,passed:6,mode:'isolated-mysql',created:first.created.length},null,2));
}
module.exports={run};
