'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
async function run({origin,actors,check,initialization=false,guiyangDemo=false}){
 const {chromium}=require(process.env.COMMERCE_PLAYWRIGHT_MODULE||'/tmp/e2e/node_modules/playwright-core');
 const browser=await chromium.launch({executablePath:process.env.COMMERCE_CHROME||'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
 const errors=[],out=path.resolve(__dirname,'../../docs/verification/newliving-commerce-m1a');fs.mkdirSync(out,{recursive:true});
 async function context(actor,width=1440){const ctx=await browser.newContext({viewport:{width,height:1000}});if(actor)await ctx.addInitScript(token=>localStorage.setItem('BZF_SESSION_TOKEN',token),actor.token);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));return {ctx,page};}
 async function ready(page){await page.waitForFunction(()=>!document.querySelector('#commerce-content')?.hasAttribute('aria-busy')&&document.querySelector('#commerce-content .commerce-card'));}
 try{
 const {ctx,page}=await context(actors.writer);
 await check('Browser platform modules render real lists without demo controls',async()=>{ // settlement/refunds/reconciliation pages need commerce.fund.read and are covered by settlement-test.cjs
  for(const file of fs.readdirSync(path.resolve(__dirname,'../../screens')).filter(v=>/^commerce-admin.*\.html$/.test(v)&&!/^commerce-admin-(settlement|refunds|reconciliation)\.html$/.test(v))){await page.goto(origin+'/screens/'+file);await ready(page);assert.equal(await page.locator('#commerce-status.error').count(),0,file);assert.equal(await page.locator('#identity').count(),0);assert(!(await page.locator('body').innerText()).includes('权益联调服务未启动'));}await page.goto(origin+'/screens/commerce-admin.html');await ready(page);await page.screenshot({path:path.join(out,'01-platform-desktop.png'),fullPage:true});});

 if(initialization)await check('Browser initialized topic details disclose unconfirmed prices and linked services',async()=>{
  await page.goto(origin+'/screens/commerce-admin-packages.html');await ready(page);await page.locator('tr').filter({hasText:'新居入住季 · 专题券包'}).getByRole('button',{name:'详情',exact:true}).click();const text=await page.locator('#commerce-dialog').innerText();assert(text.includes('待确认'));assert(text.includes('配置来源与待完善资料'));assert(text.includes('专题关联服务'));assert(!text.includes('¥0.00'));await page.screenshot({path:path.resolve(__dirname,'../../docs/verification/newliving-commerce-initialization/topic-package-detail.png'),fullPage:true});await page.getByRole('button',{name:'关闭',exact:true}).last().click();
  await page.goto(origin+'/screens/commerce-admin-plans.html');await ready(page);await page.locator('tr').filter({hasText:'新居住会员'}).getByRole('button',{name:'详情',exact:true}).click();const member=await page.locator('#commerce-dialog').innerText();assert(member.includes('999.00'));assert(member.includes('365'));await page.screenshot({path:path.resolve(__dirname,'../../docs/verification/newliving-commerce-initialization/membership-detail.png'),fullPage:true});await page.getByRole('button',{name:'关闭',exact:true}).last().click();
 });
 await check('Browser create, submit, independent review and publish a store',async()=>{
  await page.goto(origin+'/screens/commerce-admin-stores.html');await ready(page);await page.getByRole('button',{name:'新增门店',exact:true}).click();await page.locator('[name=name]').fill('浏览器验收门店');await page.locator('[name=merchant_id]').selectOption('1');await page.locator('[name=city_id]').selectOption('1');await page.locator('[name=address]').fill('验收路1号');await page.locator('[name=phone]').fill('00000000000');await page.locator('[name=capacity]').fill('4');await page.locator('[name=lead_hours]').fill('1');await page.locator('[name=description]').fill('每日九点至十八点，提前预约');await page.screenshot({path:path.join(out,'02-store-form.png'),fullPage:true});await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});
  const tr=page.locator('tr').filter({hasText:'浏览器验收门店'});await tr.getByRole('button',{name:'提交审核'}).click();await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});
  const reviewer=await context(actors.reviewer);await reviewer.page.goto(origin+'/screens/commerce-admin-stores.html');await ready(reviewer.page);await reviewer.page.locator('tr').filter({hasText:'浏览器验收门店'}).getByRole('button',{name:'复核',exact:true}).click();await reviewer.page.locator('[name=note]').fill('门店资料完整，复核通过');await reviewer.page.getByRole('button',{name:'确认保存'}).click();await reviewer.page.waitForSelector('#commerce-dialog',{state:'detached'});await reviewer.ctx.close();
  await page.reload();await ready(page);await page.locator('tr').filter({hasText:'浏览器验收门店'}).getByRole('button',{name:'发布',exact:true}).click();await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});assert((await page.locator('tr').filter({hasText:'浏览器验收门店'}).innerText()).includes('已发布'));await page.screenshot({path:path.join(out,'03-published-stores.png'),fullPage:true});
 });
 await check('Browser search empty state and published version editor',async()=>{await page.locator('[name=q]').fill('不存在的记录');await page.getByRole('button',{name:'查询',exact:true}).click();await page.waitForSelector('.commerce-empty');assert((await page.locator('#commerce-content').innerText()).includes('暂无门店管理记录'));await page.getByRole('button',{name:'重置',exact:true}).click();await page.waitForSelector('tbody tr');await page.locator('tr').filter({hasText:'浏览器验收门店'}).getByRole('button',{name:'编辑',exact:true}).click();await page.locator('[name=description]').fill('修改后需要重新审核，旧版本继续在用');await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});assert((await page.locator('tr').filter({hasText:'浏览器验收门店'}).innerText()).includes('草稿'));});
 const merchant=await context(actors.merchant);await check('Browser merchant modules scoped and platform configuration hidden',async()=>{ // fund pages (settlement/refunds/reconciliation) need commerce.fund scope; covered by settlement-test.cjs
  for(const file of fs.readdirSync(path.resolve(__dirname,'../../screens')).filter(v=>/^commerce-merchant.*\.html$/.test(v)&&!/^commerce-merchant-(settlement|refunds|reconciliation)\.html$/.test(v))){await merchant.page.goto(origin+'/screens/'+file);await ready(merchant.page);assert.equal(await merchant.page.locator('#commerce-status.error').count(),0,file);}assert.equal(await merchant.page.locator('#commerce-tabs a').filter({hasText:'报价与分配规则'}).count(),0);await merchant.page.goto(origin+'/screens/commerce-merchant.html');await ready(merchant.page);await merchant.page.screenshot({path:path.join(out,'04-merchant-desktop.png'),fullPage:true});});await merchant.ctx.close();
 await check('Browser consumer product details, personal assets and promotion share',async()=>{const user=await context(actors.user,390);await user.page.goto(origin+'/juzhu-commerce.html?city=acceptance');await ready(user.page);await user.page.getByRole('button',{name:'查看权益'}).first().click();await user.page.waitForSelector('.consumer-product-detail');assert((await user.page.locator('#commerce-content').innerText()).includes('购买暂未开放'));await user.page.goto(origin+'/juzhu-commerce.html?city=acceptance');await ready(user.page);for(const key of ['coupons','memberships','appointments','cases']){if(['orders','appointments','cases'].includes(key)){await user.page.locator('#commerce-tabs [data-tab=account]').click();await ready(user.page);await user.page.locator('#commerce-content [data-tab='+key+']').click();}else if(key==='coupons')await user.page.locator('#commerce-content [data-tab=coupons]').first().click();else await user.page.locator('#commerce-tabs [data-tab='+key+']').click();await ready(user.page);assert.equal(await user.page.locator('#commerce-status.error').count(),0);assert.equal(await user.page.locator('#account-login').isVisible(),false);}await user.page.locator('#commerce-tabs').getByRole('button',{name:'首页'}).click();await ready(user.page);await user.page.screenshot({path:path.join(out,'05-consumer-mobile.png'),fullPage:true});await user.page.goto(origin+'/juzhu-promoter.html');await ready(user.page);assert((await user.page.locator('.promoter-mini').count())>0,'compact promoter product cards');const catalogText=await user.page.locator('#commerce-content').innerText();assert(catalogText.includes('演示 · 无佣金')&&catalogText.includes('点击'),'commission and per-product stats on cards');assert.equal(await user.page.locator('.promoter-sort [data-psort]').count(),6,'sort chips rendered');assert.equal(await user.page.locator('[data-pf-kind]').count(),4,'kind filter chips rendered');
await user.page.locator('[data-psort=rate]').click();await user.page.waitForFunction(()=>document.querySelectorAll('#promoter-grid .promoter-mini').length>0,'resort renders grid');await user.page.locator('[data-psort=default]').click();
await user.page.locator('[data-pf-kind=plans]').click();await user.page.waitForFunction(()=>{const ks=[...document.querySelectorAll('#promoter-grid .pm-kind')];return ks.length>0&&ks.every(k=>k.textContent==='会员');},'kind filter narrows grid');
await user.page.locator('[data-pf-kind=""]').click();await user.page.locator('[data-pf-toggle=commission]').click();await user.page.waitForFunction(()=>document.querySelectorAll('#promoter-grid .pm-comm.is-demo').length===0,'commission filter hides demo cards');
await user.page.locator('[data-pf-toggle=commission]').click();await user.page.waitForFunction(()=>document.querySelectorAll('#promoter-grid .pm-comm.is-demo').length>0,'filter reset restores demo cards');
// 归因购买必须是演示商品（分享与购买同品），按目录里第一个演示商品的卡位确定性分享。
const demoName=await user.page.evaluate(async()=>{const cat=(await (await fetch('/api/commerce/v1/catalog')).json()).data||[];const d=cat.find(x=>x.is_demo);return d?d.name:null;});assert(demoName,'demo product exists for attribution');
const demoIdx=await user.page.evaluate(name=>[...document.querySelectorAll('#promoter-grid .promoter-mini h3')].findIndex(h=>h.textContent===name),demoName);assert(demoIdx>=0,'demo card present in grid: '+demoName);
await user.page.locator('#promoter-grid .promoter-mini [data-action=product]').nth(demoIdx).click();await user.page.getByRole('button',{name:'生成分享链接'}).click();await user.page.waitForSelector('#share-result textarea');const shareUrl=await user.page.locator('#share-result textarea').inputValue();assert(shareUrl.includes('&ref='));await user.ctx.grantPermissions(['clipboard-read','clipboard-write'],{origin});await user.page.getByRole('button',{name:'复制链接'}).click();await user.page.waitForFunction(()=>document.querySelector('.copy-share')?.textContent==='已复制','share link copy button confirms');assert((await user.page.evaluate(()=>navigator.clipboard.readText())).includes('&ref='),'clipboard holds share url');await user.page.locator('.dialog-close').click();assert.equal(await user.page.locator('#account-login').isVisible(),false,'promoter logged-in hides login');assert.equal(await user.page.locator('#account-logout').isVisible(),true,'promoter logged-in shows logout');await user.page.screenshot({path:path.join(out,'06-promoter-share-390.png'),fullPage:true});
// 用分享链接让另一账号归因下一笔演示单，推广看板（明细/归因订单）即有真实数据可渲染。
const attributed=await user.page.evaluate(async({token,url})=>{try{const u=new URL(url);const [kind,pid]=u.searchParams.get('product').split('-');const cat=(await (await fetch('/api/commerce/v1/catalog')).json()).data||[];const p=cat.find(x=>x.kind===kind&&x.id===Number(pid));if(!p)return 'no-product';const res=await fetch('/api/commerce/v1/demo-orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({kind,product_id:Number(pid),version:p.version,demo_ack:true,referral:u.searchParams.get('ref')})});return res.status;}catch(e){return 'error:'+e.message;}},{token:actors.other.token,url:shareUrl});assert.equal(attributed,201,'browser attribution seeds records: '+attributed);
await user.page.locator('#commerce-tabs [data-tab=promotion]').click();await ready(user.page);const promoText=await user.page.locator('#commerce-content').innerText();assert(promoText.includes('我的推广')&&promoText.includes('暂不支持自主提现'),'promotion tab discloses settlement and withdrawal');assert(promoText.includes('资格')&&promoText.includes('演示期开放'),'qualification state disclosed');for(const section of ['佣金明细','归因订单','代发 / 到账记录'])assert(promoText.includes(section),'records section rendered: '+section);assert.equal(await user.page.locator('.promoter-fold[open]').count(),0,'record folds start collapsed');
await user.page.locator('[data-open=orders]').click();await user.page.waitForFunction(()=>document.querySelector('#fold-orders')?.open===true,'kpi click expands orders fold');
const openText=await user.page.locator('#commerce-content').innerText();assert(openText.includes('演示'),'attributed demo order visible after expand');await user.page.screenshot({path:path.join(out,'07-promoter-kpi-390.png'),fullPage:true});const anon=await context(null,390);await anon.page.goto(origin+'/juzhu-promoter.html');await ready(anon.page);assert.equal(await anon.page.locator('#account-login').isVisible(),true,'anonymous sees login');assert.equal(await anon.page.locator('#account-logout').isVisible(),false,'anonymous has no logout');await anon.ctx.close();await user.ctx.close();});
 await check('Browser four entry pages responsive at 390px and 1440px',async()=>{for(const width of [390,1440])for(const [file,actor]of [['juzhu-commerce.html',null],['juzhu-promoter.html',actors.user],['screens/commerce-admin.html',actors.writer],['screens/commerce-merchant.html',actors.merchant]]){const device=await context(actor,width);await device.page.goto(origin+'/'+file);await ready(device.page);assert(await device.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),file+' overflow '+width);if(width===390&&file.startsWith('screens/'))assert.equal(await device.page.locator('.nv-side').isVisible(),false);await device.ctx.close();}});
 await check('Browser anonymous, permission denial, server failure and retry states',async()=>{const anon=await context();await anon.page.goto(origin+'/screens/commerce-admin.html');await ready(anon.page);assert((await anon.page.locator('#commerce-content').innerText()).includes('登录后'));await anon.ctx.close();const user=await context(actors.user);await user.page.goto(origin+'/screens/commerce-admin.html');await ready(user.page);assert((await user.page.locator('#commerce-content').innerText()).includes('暂无访问权限'));await user.ctx.close();await page.route('**/api/commerce/v1/catalog',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'暂时无法加载'})}));await page.goto(origin+'/juzhu-commerce.html');await ready(page);assert((await page.locator('#commerce-content').innerText()).includes('暂时无法加载'));await page.unroute('**/api/commerce/v1/catalog');await page.getByRole('button',{name:'重新加载'}).click();await page.waitForSelector('.product-card');});
 if(guiyangDemo)await check('Browser single-voucher filtering, acknowledged checkout and member gift delivery',async()=>{
  const user=await context(actors.user,390);const output=path.resolve(__dirname,'../../docs/verification/guiyang-life-demo');fs.mkdirSync(output,{recursive:true});
  try{
   await user.page.goto(origin+'/juzhu-vouchers.html?city=guiyang');await ready(user.page);
   await user.page.locator('#consumer-category').selectOption('cleaning');assert.equal(await user.page.locator('.product-card').count(),6);
   await user.page.screenshot({path:path.join(output,'single-vouchers-390.png')});
   const before=await user.page.evaluate(async()=> (await COMMERCE.api('/my')).coupons.length);
   await user.page.getByRole('button',{name:'查看权益',exact:true}).first().click();await user.page.waitForSelector('.consumer-product-detail');await user.page.getByRole('button',{name:'演示购买',exact:true}).click();
   assert((await user.page.locator('#commerce-dialog').innerText()).includes('实际支付 ¥0.00'));
   await user.page.screenshot({path:path.join(output,'single-checkout-390.png')});
   await user.page.locator('[name=demo_ack]').check();await user.page.getByRole('button',{name:'确认演示购买',exact:true}).click();await user.page.waitForURL('**/juzhu-commerce.html?view=coupons**');await ready(user.page);
   assert.equal(await user.page.evaluate(async()=> (await COMMERCE.api('/my')).coupons.length),before+1);assert((await user.page.locator('#commerce-content').innerText()).includes('演示权益'));await user.page.locator('[data-action=coupon-detail]').first().click();await user.page.waitForSelector('.consumer-view-heading h1');assert((await user.page.locator('#commerce-content').innerText()).includes('卡券编号'));await user.page.screenshot({path:path.join(output,'owned-voucher-detail-390.png')});
   await user.page.goto(origin+'/juzhu-vouchers.html?city=guiyang&kind=plans');await ready(user.page);await user.page.getByRole('button',{name:'查看权益',exact:true}).click();await user.page.waitForSelector('.consumer-product-detail');await user.page.getByRole('button',{name:'购买演示会员',exact:true}).click();await user.page.locator('[name=demo_ack]').check();await user.page.getByRole('button',{name:'确认演示购买',exact:true}).click();await user.page.waitForURL('**/juzhu-commerce.html?view=coupons**');await ready(user.page);assert.equal(await user.page.evaluate(async()=> (await COMMERCE.api('/my')).coupons.length),before+6);
   assert(await user.page.evaluate(()=>document.querySelector('.scr').scrollWidth<=document.querySelector('.scr').clientWidth));
   await user.page.locator('#commerce-tabs [data-tab=memberships]').click();await ready(user.page);await user.page.screenshot({path:path.join(output,'member-delivered-390.png')});
  }finally{await user.ctx.close();}
 });
 if(guiyangDemo)await require('./member-exchange-browser.cjs').run({browser,origin,actors,check});
 await ctx.close();await check('Browser no uncaught JavaScript errors',async()=>assert.deepEqual(errors,[]));
 }finally{await browser.close();}
}
module.exports={run};
