'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
async function run({origin,actors,check,initialization=false,guiyangDemo=false}){
 const {chromium}=require(process.env.COMMERCE_PLAYWRIGHT_MODULE||'/tmp/e2e/node_modules/playwright-core');
 const browser=await chromium.launch({executablePath:process.env.COMMERCE_CHROME||'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
 const errors=[],out=path.resolve(__dirname,'../../docs/verification/newliving-commerce-m1a');fs.mkdirSync(out,{recursive:true});
 async function context(actor,width=1440){const ctx=await browser.newContext({viewport:{width,height:1000}});if(actor)await ctx.addInitScript(token=>localStorage.setItem('BZF_SESSION_TOKEN',token),actor.token);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));return {ctx,page};}
 async function ready(page){await page.waitForFunction(()=>!document.querySelector('#commerce-content')?.hasAttribute('aria-busy')&&document.querySelector('#commerce-content .commerce-card'));}
 try{
 const {ctx,page}=await context(actors.writer);
 await check('Browser platform modules render real lists without demo controls',async()=>{ // settlement/refunds/reconciliation pages need commerce.fund.read and are covered by settlement-test.cjs
  for(const file of fs.readdirSync(path.resolve(__dirname,'../../screens')).filter(v=>/^commerce-admin.*\.html$/.test(v)&&!/^commerce-admin-(settlement|refunds|reconciliation)\.html$/.test(v))){await page.goto(origin+'/screens/'+file);await ready(page);assert.equal(await page.locator('#commerce-status.error').count(),0,file);assert.equal(await page.locator('#identity').count(),0);assert(!(await page.locator('body').innerText()).includes('权益联调服务未启动'));}await page.goto(origin+'/screens/commerce-admin.html');await ready(page);await page.screenshot({path:path.join(out,'01-platform-desktop.png'),fullPage:true});});

 if(initialization)await check('Browser initialized topic details disclose unconfirmed prices and linked services',async()=>{
  await page.goto(origin+'/screens/commerce-admin-packages.html');await ready(page);await page.locator('tr').filter({hasText:'新居入住季 · 专题券包'}).getByRole('button',{name:'详情',exact:true}).click();const text=await page.locator('#commerce-dialog').innerText();assert(text.includes('待确认'));assert(text.includes('配置来源与待完善资料'));assert(text.includes('专题关联服务'));assert(!text.includes('¥0.00'));await page.screenshot({path:path.resolve(__dirname,'../../docs/verification/newliving-commerce-initialization/topic-package-detail.png'),fullPage:true});await page.getByRole('button',{name:'关闭',exact:true}).last().click();
  await page.goto(origin+'/screens/commerce-admin-plans.html');await ready(page);await page.locator('tr').filter({hasText:'新居住会员'}).getByRole('button',{name:'详情',exact:true}).click();const member=await page.locator('#commerce-dialog').innerText();assert(member.includes('999.00'));assert(member.includes('365'));await page.screenshot({path:path.resolve(__dirname,'../../docs/verification/newliving-commerce-initialization/membership-detail.png'),fullPage:true});await page.getByRole('button',{name:'关闭',exact:true}).last().click();
 });
 await check('Browser create, submit, independent review and publish a store',async()=>{
  await page.goto(origin+'/screens/commerce-admin-stores.html');await ready(page);await page.getByRole('button',{name:'新增门店',exact:true}).click();await page.locator('[name=name]').fill('浏览器验收门店');await page.locator('[name=merchant_id]').selectOption('1');await page.locator('[name=city_id]').selectOption('1');await page.locator('[name=address]').fill('验收路1号');await page.locator('[name=phone]').fill('00000000000');await page.locator('[name=capacity]').fill('4');await page.locator('[name=lead_hours]').fill('1');await page.locator('[name=description]').fill('每日九点至十八点，提前预约');await page.screenshot({path:path.join(out,'02-store-form.png'),fullPage:true});await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});
  const tr=page.locator('tr').filter({hasText:'浏览器验收门店'});await tr.getByRole('button',{name:'提交审核'}).click();await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});
  const reviewer=await context(actors.reviewer);await reviewer.page.goto(origin+'/screens/commerce-admin-stores.html');await ready(reviewer.page);await reviewer.page.locator('tr').filter({hasText:'浏览器验收门店'}).getByRole('button',{name:'复核',exact:true}).click();await reviewer.page.locator('[name=note]').fill('门店资料完整，复核通过');await reviewer.page.getByRole('button',{name:'确认保存'}).click();await reviewer.page.waitForSelector('#commerce-dialog',{state:'detached'});await reviewer.ctx.close();
  await page.reload();await ready(page);await page.locator('tr').filter({hasText:'浏览器验收门店'}).getByRole('button',{name:'发布',exact:true}).click();await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});assert((await page.locator('tr').filter({hasText:'浏览器验收门店'}).innerText()).includes('已发布'));await page.screenshot({path:path.join(out,'03-published-stores.png'),fullPage:true});
 });
 await check('Browser search empty state and published version editor',async()=>{await page.locator('[name=q]').fill('不存在的记录');await page.getByRole('button',{name:'查询',exact:true}).click();await page.waitForSelector('.commerce-empty');assert((await page.locator('#commerce-content').innerText()).includes('暂无门店管理记录'));await page.getByRole('button',{name:'重置',exact:true}).click();await page.waitForSelector('tbody tr');await page.locator('tr').filter({hasText:'浏览器验收门店'}).getByRole('button',{name:'编辑',exact:true}).click();await page.locator('[name=description]').fill('修改后需要重新审核，旧版本继续在用');await page.getByRole('button',{name:'确认保存'}).click();await page.waitForSelector('#commerce-dialog',{state:'detached'});assert((await page.locator('tr').filter({hasText:'浏览器验收门店'}).innerText()).includes('草稿'));});
 const merchant=await context(actors.merchant);await check('Browser merchant modules scoped and platform configuration hidden',async()=>{ // fund pages (settlement/refunds/reconciliation) need commerce.fund scope; covered by settlement-test.cjs
  for(const file of fs.readdirSync(path.resolve(__dirname,'../../screens')).filter(v=>/^commerce-merchant.*\.html$/.test(v)&&!/^commerce-merchant-(settlement|refunds|reconciliation)\.html$/.test(v))){await merchant.page.goto(origin+'/screens/'+file);await ready(merchant.page);assert.equal(await merchant.page.locator('#commerce-status.error').count(),0,file);}assert.equal(await merchant.page.locator('#commerce-tabs a').filter({hasText:'报价与分配规则'}).count(),0);await merchant.page.goto(origin+'/screens/commerce-merchant.html');await ready(merchant.page);await merchant.page.screenshot({path:path.join(out,'04-merchant-desktop.png'),fullPage:true});});await merchant.ctx.close();
 await check('Browser consumer product details, personal assets and promotion share',async()=>{const user=await context(actors.user,390);await user.page.goto(origin+'/juzhu-commerce.html?city=acceptance');await ready(user.page);await user.page.getByRole('button',{name:'查看权益'}).first().click();await user.page.waitForSelector('.consumer-product-detail');assert((await user.page.locator('#commerce-content').innerText()).includes('购买暂未开放'));await user.page.goto(origin+'/juzhu-commerce.html?city=acceptance');await ready(user.page);for(const key of ['coupons','memberships','appointments','cases']){if(['orders','appointments','cases'].includes(key)){await user.page.locator('#commerce-tabs [data-tab=account]').click();await ready(user.page);await user.page.locator('#commerce-content [data-tab='+key+']').click();}else if(key==='coupons')await user.page.locator('#commerce-content [data-tab=coupons]').first().click();else await user.page.locator('#commerce-tabs [data-tab='+key+']').click();await ready(user.page);assert.equal(await user.page.locator('#commerce-status.error').count(),0);assert.equal(await user.page.locator('#account-login').isVisible(),false);}await user.page.locator('#commerce-tabs').getByRole('button',{name:'首页'}).click();await ready(user.page);await user.page.screenshot({path:path.join(out,'05-consumer-mobile.png'),fullPage:true});await user.page.goto(origin+'/juzhu-promoter.html');await ready(user.page);await user.page.getByRole('button',{name:'查看并分享'}).first().click();await user.page.getByRole('button',{name:'生成分享链接'}).click();await user.page.waitForSelector('#share-result textarea');assert((await user.page.locator('#share-result textarea').inputValue()).includes('&ref='));await user.ctx.close();});
 await check('Browser four entry pages responsive at 390px and 1440px',async()=>{for(const width of [390,1440])for(const [file,actor]of [['juzhu-commerce.html',null],['juzhu-promoter.html',actors.user],['screens/commerce-admin.html',actors.writer],['screens/commerce-merchant.html',actors.merchant]]){const device=await context(actor,width);await device.page.goto(origin+'/'+file);await ready(device.page);assert(await device.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),file+' overflow '+width);if(width===390&&file.startsWith('screens/'))assert.equal(await device.page.locator('.nv-side').isVisible(),false);await device.ctx.close();}});
 await check('Browser anonymous, permission denial, server failure and retry states',async()=>{const anon=await context();await anon.page.goto(origin+'/screens/commerce-admin.html');await ready(anon.page);assert((await anon.page.locator('#commerce-content').innerText()).includes('登录后'));await anon.ctx.close();const user=await context(actors.user);await user.page.goto(origin+'/screens/commerce-admin.html');await ready(user.page);assert((await user.page.locator('#commerce-content').innerText()).includes('暂无访问权限'));await user.ctx.close();await page.route('**/api/commerce/v1/catalog',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'暂时无法加载'})}));await page.goto(origin+'/juzhu-commerce.html');await ready(page);assert((await page.locator('#commerce-content').innerText()).includes('暂时无法加载'));await page.unroute('**/api/commerce/v1/catalog');await page.getByRole('button',{name:'重新加载'}).click();await page.waitForSelector('.product-card');});
 if(guiyangDemo)await check('Browser single-voucher filtering, acknowledged checkout and member gift delivery',async()=>{
  const user=await context(actors.user,390);const output=path.resolve(__dirname,'../../docs/verification/guiyang-life-demo');fs.mkdirSync(output,{recursive:true});
  try{
   await user.page.goto(origin+'/juzhu-vouchers.html?city=guiyang');await ready(user.page);
   await user.page.locator('#consumer-category').selectOption('cleaning');assert.equal(await user.page.locator('.product-card').count(),6);
   await user.page.screenshot({path:path.join(output,'single-vouchers-390.png')});
   const before=await user.page.evaluate(async()=> (await COMMERCE.api('/my')).coupons.length);
   await user.page.getByRole('button',{name:'查看权益',exact:true}).first().click();await user.page.waitForSelector('.consumer-product-detail');await user.page.getByRole('button',{name:'演示购买',exact:true}).click();
   assert((await user.page.locator('#commerce-dialog').innerText()).includes('实际支付 ¥0.00'));
   await user.page.screenshot({path:path.join(output,'single-checkout-390.png')});
   await user.page.locator('[name=demo_ack]').check();await user.page.getByRole('button',{name:'确认演示购买',exact:true}).click();await user.page.waitForURL('**/juzhu-commerce.html?view=coupons**');await ready(user.page);
   assert.equal(await user.page.evaluate(async()=> (await COMMERCE.api('/my')).coupons.length),before+1);assert((await user.page.locator('#commerce-content').innerText()).includes('演示权益'));await user.page.locator('[data-action=coupon-detail]').first().click();await user.page.waitForSelector('.consumer-view-heading h1');assert((await user.page.locator('#commerce-content').innerText()).includes('卡券编号'));await user.page.screenshot({path:path.join(output,'owned-voucher-detail-390.png')});
   await user.page.goto(origin+'/juzhu-vouchers.html?city=guiyang&kind=plans');await ready(user.page);await user.page.getByRole('button',{name:'查看权益',exact:true}).click();await user.page.waitForSelector('.consumer-product-detail');await user.page.getByRole('button',{name:'购买演示会员',exact:true}).click();await user.page.locator('[name=demo_ack]').check();await user.page.getByRole('button',{name:'确认演示购买',exact:true}).click();await user.page.waitForURL('**/juzhu-commerce.html?view=coupons**');await ready(user.page);assert.equal(await user.page.evaluate(async()=> (await COMMERCE.api('/my')).coupons.length),before+6);
   assert(await user.page.evaluate(()=>document.querySelector('.scr').scrollWidth<=document.querySelector('.scr').clientWidth));
   await user.page.locator('#commerce-tabs [data-tab=memberships]').click();await ready(user.page);await user.page.screenshot({path:path.join(output,'member-delivered-390.png')});
  }finally{await user.ctx.close();}
 });
 if(guiyangDemo)await require('./member-exchange-browser.cjs').run({browser,origin,actors,check});
 await ctx.close();await check('Browser no uncaught JavaScript errors',async()=>assert.deepEqual(errors,[]));
 }finally{await browser.close();}
}
module.exports={run};
