'use strict';
// Local browser contract regression. Starts only a loopback fixture server; never calls the application database or payment provider.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.COMMERCE_PLAYWRIGHT_MODULE || '/tmp/e2e/node_modules/playwright-core');
const root=path.resolve(__dirname,'../..'),base='/api/settlement/v1',posts=[];
const item={id:'it-1',context_id:'ctx-1',biz_type:'jiazheng',payment_mode:'pay_center',beneficiary_party_id:'1',line_kind:'merchant',unit_id:'unit-1',payable_minor:'20000',planned_minor:'18000',discharged_minor:'0',remaining_minor:'20000',revision:2,status:'READY',account_id:'acc-1',not_before_at:'2026-10-02T10:00:00Z',context:{biz_order_no:'JZ-20261002'},adjustments:[],execution_orders:[{id:'ex-1',amount_minor:'18000',status:'UNKNOWN'}]};
const statement={id:'st-1',statement_no:'ST-202610',party_id:'1',currency:'CNY',period_start:'2026-08-31 16:00:00',period_end:'2026-09-30 16:00:00',as_of:'2026-10-02T10:00:00Z',version:2,publication_status:'PUBLISHED',recon_status:'UNVERIFIED',coverage_status:'INCOMPLETE',summary:{opening_minor:'0',accrued_minor:'20000',closing_minor:'20000',unknown_amount_count:1,external_receivable_accrued_minor:'1000',external_payable_accrued_minor:'500'},snapshot:{summary:{opening_minor:'0',accrued_minor:'20000',closing_minor:'20000',unknown_amount_count:1,external_receivable_accrued_minor:'1000',external_payable_accrued_minor:'500'},lines:[{line_key:'l1',biz_type:'jiazheng',payment_mode:'wechat_mini',record_type:'EXTERNAL_ORDER',event_kind:'PAYMENT',order_ref:'EXT-1',amount_minor:null,verification_status:'UNVERIFIED',note:'金额待补'}]}};
const ownSource={id:'receipt-1',source_id:'source-1',context_id:'ctx-1',party_id:'1',amount_minor:'100000',provider_reference:'BANK-OWN-1',evidence_ref:'bank-proof',status:'APPROVED',created_by:'different-actor'};
const compensation={id:'comp-1',context_id:'ctx-1',beneficiary_party_id:'customer-1',original_unit_id:'unit-1',source_id:'source-1',amount_minor:'2000',case_ref:'CASE-1',evidence_ref:'comp-proof',reason:'服务补偿',status:'DRAFT',created_by:'different-actor'};
let mode='admin',acceptance={eligible:true,confirmed:false,reason:'服务已完成，请核对后验收'};
for (const name of ['juzhu-jiazheng-order-detail.html','jiazheng-order.html']) assert(fs.readFileSync(path.join(root,name),'utf8').includes('screens/_settlement-acceptance.js'));
new (require('node:vm').Script)(fs.readFileSync(path.join(root,'screens/_settlement-acceptance.js'),'utf8'));
const identity=()=>({account:{id:'7',display_name:'测试财务<img src=x onerror="window.__xss=true">'},permissions:mode==='recipient'?['settlement.statement.read','settlement.statement.export','settlement.statement.confirm','settlement.statement.dispute','settlement.external.submit']:['*'],parties:[{id:'1',name:'示例服务商 <img src=x onerror="window.__xss=true">'}],scope:{}});
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');const p=u.pathname;let raw='';for await(const chunk of req)raw+=chunk;const body=raw?JSON.parse(raw):null;const send=(data,code=200)=>{res.writeHead(code,{'content-type':'application/json'});res.end(JSON.stringify({data}));};if(p.startsWith(base)){if(mode==='unauth'){res.writeHead(401,{'content-type':'application/json'});res.end(JSON.stringify({error:'请登录'}));return;}if(req.method==='POST')posts.push({path:p,body,key:req.headers['idempotency-key'],authorization:req.headers.authorization});
if(p===base+'/me')return send(identity());
if(p===base+'/admin/own-fund-sources'&&req.method==='GET')return send({rows:[ownSource,{...ownSource,id:'receipt-draft',status:'DRAFT'}]});
if(p===base+'/admin/compensations'&&req.method==='GET')return send({rows:[compensation]});
if(p===base+'/admin/compensation-recoveries'&&req.method==='GET')return send({rows:[{id:'rec-1',compensation_id:'comp-1',amount_minor:'2000',activated_minor:'0',debtor_party_id:'1',status:'PENDING_PAYMENT'}]});
if(p===base+'/admin/funding-sources')return send({rows:[{id:'fund-1',available_minor:'10000'}]});
if(p===base+'/admin/configuration/accounts'&&req.method==='GET')return send({rows:[{id:'ca-1',party_id:'1',provider:'acn',environment:'sandbox',merchant_no:'merchant123',contract_no:'c-1',capabilities:{receive:true,evidence_ref:'proof-1',operations:['SPLIT']},status:'draft',created_by:'different-actor'}]});
if(p===base+'/admin/configuration/profiles'&&req.method==='GET')return send({rows:[]});
if(p===base+'/me/service-orders/order-accept/acceptance'){if(req.method==='POST')acceptance={eligible:false,confirmed:true};return send(acceptance);}
if(p===base+'/admin/items')return send({rows:[item,{...item,id:'it-big',payable_minor:'900719925474099301',planned_minor:'900719925474099301',hold_reason:'<svg onload="window.__xss=true">'}]});
if(p===base+'/admin/items/it-1')return send(item);
if(p===base+'/admin/accounts')return send({rows:[{id:'acc-1',party_id:'1',merchant_no:'merchant123',status:'APPROVED',provider:'acn',environment:'sandbox',contract_no:'c-1',capabilities:{own_funds_verified:true,receive:true,operations:['SPLIT','PAYOUT']}},{id:'other',party_id:'2',merchant_no:'should-hide',status:'APPROVED'},{id:'customer-acc',party_id:'customer-1',merchant_no:'customer123',status:'APPROVED',capabilities:{receive:true}}]});
if(p.endsWith('/adjustments/preview'))return send({before:item,after:{...item,planned_minor:body.planned_minor},requires_review:true});
if(p.endsWith('/adjustments'))return send({revision:3,status:'IN_REVIEW'});
if(p===base+'/admin/policies'&&req.method==='GET')return send({rows:[{id:'po-1',biz_type:'jiazheng',mode:'REVIEW',priority:100,version:1,status:'DRAFT',nodes:[{name:'财务复核'}]},{id:'po-active',biz_type:'jiazheng',mode:'AUTO',priority:99,version:1,status:'ACTIVE',nodes:[]}]});
if(p===base+'/admin/approval-tasks')return send({rows:[{id:'ap-1',item_id:'it-1',revision:2,node_name:'财务复核',status:'PENDING'}]});
if(p===base+'/admin/external-evidence'&&req.method==='GET')return send({rows:[{id:'event-1',party_id:'1',channel:'external',event_kind:'PAYMENT',amount_minor:'20000',verification_status:'UNVERIFIED',evidence:[{id:'evidence-1',evidence_ref:'proof-1',review_status:'PENDING'}]}]});
if(p===base+'/me/settlement-statements')return send({rows:[statement]});
if(p===base+'/me/settlement-statements/st-1')return send(statement);
if(p.endsWith('/exports'))return send({id:'export-'+body.format,status:'QUEUED'});
if(p.includes('/statement-exports/')&&p.endsWith('/download')){res.writeHead(200,{'content-type':'application/octet-stream'});res.end('test-download');return;}
if(p.includes('/statement-exports/'))return send({id:p.split('/').pop(),status:'READY'});
return send({status:'SUCCESS',id:'result'});}
if(p==='/acceptance-harness'){res.writeHead(200,{'content-type':'text/html'});res.end('<!doctype html><html><head><meta charset="utf-8"></head><body><main class="scr"></main><script src="/screens/_settlement-acceptance.js"></script></body></html>');return;}
if(p==='/favicon.ico'){res.writeHead(204);res.end();return;}
const f=path.join(root,decodeURIComponent(p));try{res.writeHead(200,{'content-type':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end('not found');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({executablePath:process.env.COMMERCE_CHROME || '/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('BZF_SESSION_TOKEN','local-ui-test-token'));
await page.goto(origin+'/screens/settlement-admin.html');await page.getByText('逐笔应结',{exact:true}).waitFor();assert(await page.getByText('¥9,007,199,254,740,993.01',{exact:true}).count()>0);assert.equal(await page.evaluate(()=>!!window.__xss),false);await page.screenshot({path:'/tmp/settlement-admin-desktop.png',fullPage:true});
await page.locator('[data-action=item][data-id="it-1"]').click();await page.locator('dialog [data-action=adjust]').click();assert.equal(await page.locator('dialog [name=account_id] option[value=other]').count(),0);await page.locator('dialog [name=planned]').fill('150.00');await page.locator('dialog [name=reason]').fill('分期支付，保留剩余应付');await page.locator('dialog [type=submit]').click();await page.getByRole('button',{name:'确认提交调整',exact:true}).waitFor();await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));const adj=posts.find(p=>p.path.endsWith('/adjustments'));assert.equal(adj.body.planned_minor,'15000');assert.equal(adj.body.expected_revision,2);assert(adj.key);assert.equal(adj.authorization,'Bearer local-ui-test-token');
await page.locator('[data-action=tab][data-id=policies]').click();await page.locator('[data-action=new-policy]').click();await page.locator('dialog [name=mode]').selectOption('AUTO');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert.equal(posts.find(p=>p.path.endsWith('/policies')).body.nodes.length,0);
await page.locator('[data-action=tab][data-id=approvals]').click();await page.locator('[data-action=approval]').click();await page.locator('dialog [name=note]').fill('付款依据及账户已核对');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert.equal(posts.find(p=>p.path.endsWith('/actions')).body.revision,2);
await page.locator('[data-action=tab][data-id=external]').click();await page.locator('[data-action=review-evidence]').click();await page.locator('dialog [name=note]').fill('已核验银行流水');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert(posts.some(p=>p.path.endsWith('/external-evidence/evidence-1/reviews')));
await page.locator('[data-action=tab][data-id=configuration]').click();await page.locator('[data-action=new-configuration]').click();await page.locator('dialog [name=provider]').fill('acn');await page.locator('dialog [name=merchant_no]').fill('newmerchant');await page.locator('dialog [name=contract_no]').fill('contract-proof');await page.locator('dialog [name=evidence_ref]').fill('institution-verification');await page.locator('dialog [name=receive]').check();assert.equal(await page.locator('dialog [name=own_funds_verified]').isChecked(),false);await page.locator('dialog [name=own_funds_verified]').check();await page.locator('dialog [name=own_funds_evidence_ref]').fill('independent-cash-proof');await page.locator('dialog [name=operation][value=PAYOUT]').check();await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert.equal(posts.find(p=>p.path.endsWith('/configuration/accounts')).body.capabilities.receive,true);assert.equal(posts.find(p=>p.path.endsWith('/configuration/accounts')).body.capabilities.own_funds_evidence_ref,'independent-cash-proof');
await page.locator('[data-action=review-configuration]').click();await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert(posts.some(p=>p.path.endsWith('/configuration/accounts/ca-1/approve')));
await page.locator('[data-action=config-kind][data-id=profiles]').click();await page.locator('[data-action=new-configuration]').click();
for(const [key,value] of Object.entries({contract_ref:'LIFE-2026',commission_percent:'12.34',channel_percent:'5.67',contract_no:'c-1',collection_mapping_version:'collection-v2',contract_mapping_version:'settlement-v4',funding_evidence_ref:'funding-proof'}))await page.locator('dialog [name='+key+']').fill(value);
await page.locator('dialog [name=rounding]').selectOption('FLOOR_BPS_V1');for(const key of ['source_account_id','merchant_account_id','platform_account_id'])await page.locator('dialog [name='+key+']').selectOption('acc-1');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));const profile=posts.find(p=>p.path.endsWith('/configuration/profiles')).body.snapshot;assert.equal(profile.calculation.commission_bps,1234);assert.equal(profile.calculation.channel_bps,567);assert.deepEqual(profile.collection,{mapping_version:'collection-v2',contract_no:'c-1',source_merchant_no:'merchant123',provider:'acn',environment:'sandbox'});assert.equal(profile.contract_mapping_version,'settlement-v4');
await page.locator('[data-action=tab][data-id=policies]').click();await page.locator('[data-action=disable-policy]').click();await page.getByText('未发送明细重新匹配策略，已发送按原单查结果。停用后可发布替代规则。',{exact:true}).waitFor();await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert(posts.some(p=>p.path.endsWith('/policies/po-active/disable')));
await page.locator('[data-action=tab][data-id=own-funds]').click();await page.locator('[data-action=new-own-source]').click();await page.locator('dialog [name=context_id]').selectOption('ctx-1');await page.locator('dialog [name=account_id]').selectOption('acc-1');await page.locator('dialog [name=amount]').fill('1000.01');await page.locator('dialog [name=provider_reference]').fill('BANK-OWN-2');await page.locator('dialog [name=evidence_ref]').fill('independent-bank-transfer');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert.equal(posts.find(p=>p.path.endsWith('/own-fund-sources')).body.amount_minor,'100001');
await page.locator('[data-action=review-own-source][data-id=receipt-draft]').click();await page.locator('dialog [name=note]').fill('已验证独立平台入账');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert(posts.some(p=>p.path.endsWith('/own-fund-sources/receipt-draft/approve')));
await page.locator('[data-action=own-funds-kind][data-id=compensations]').click();await page.locator('[data-action=new-compensation]').click();for(const [name,value] of [['context_id','ctx-1'],['original_unit_id','unit-1'],['source_id','source-1'],['account_id','customer-acc']])await page.locator('dialog [name='+name+']').selectOption(value);for(const [name,value] of [['amount','20.00'],['case_ref','AFTERSALE-2'],['evidence_ref','case-proof'],['reason','已履约服务差额赔付']])await page.locator('dialog [name='+name+']').fill(value);await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));const comp=posts.find(p=>p.path.endsWith('/compensations')).body;assert.equal(comp.amount_minor,'2000');assert.equal(comp.original_unit_id,'unit-1');assert.equal(comp.source_id,'source-1');
await page.locator('[data-action=review-compensation]').click();await page.locator('dialog [name=note]').fill('独立复核赔付资料');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert(posts.some(p=>p.path.endsWith('/compensations/comp-1/approve')));
await page.locator('[data-action=own-funds-kind][data-id=recoveries]').click();await page.getByRole('columnheader',{name:'已形成应收',exact:true}).waitFor();
mode='recipient';await page.goto(origin+'/screens/settlement-statements.html');await page.getByText('2026-09-01 至 2026-10-01',{exact:true}).waitFor();await page.locator('[data-action=statement]').click();await page.getByText('有 1 条记录金额待补',{exact:false}).waitFor();assert.equal(await page.locator('[data-action=generate-statement]').count(),0);assert.equal(await page.locator('[name=party_id] option').count(),1);for(const fmt of ['csv','xlsx','pdf']){const downloaded=page.waitForEvent('download');await page.locator('[data-action=export-'+fmt+']').click();const file=await downloaded;assert(file.suggestedFilename().endsWith('.'+fmt));}await page.getByText('本期佣金应收',{exact:true}).waitFor();await page.getByText('本期佣金应付',{exact:true}).waitFor();await page.screenshot({path:'/tmp/settlement-statement-desktop.png',fullPage:true});await page.locator('[data-action=dispute-statement]').click();assert.equal(await page.locator('dialog [name=evidence_ref]').getAttribute('required'),'');assert.equal(await page.locator('dialog [name=note]').getAttribute('maxlength'),'1000');await page.locator('dialog [name=evidence_ref]').fill('dispute-proof');await page.locator('dialog [name=note]').fill('申请核对外部收款');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert(posts.some(p=>p.path.endsWith('/disputes')&&p.body.evidence_ref==='dispute-proof'));await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/settlement-statements-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.goto(origin+'/acceptance-harness?order_ref=order-accept');await page.getByRole('button',{name:'确认服务完成',exact:true}).click();await page.locator('dialog [name=accepted]').check();await page.locator('dialog [name=note]').fill('约定服务已全部完成');await page.locator('dialog [type=submit]').click();await page.getByText('您已确认本次服务完成。结算将按商户约定继续处理。',{exact:true}).waitFor();assert(posts.some(p=>p.path.endsWith('/service-orders/order-accept/acceptance')&&p.key&&p.body.note));
acceptance={eligible:false,confirmed:false,reason:'当前合同尚未满足验收条件'};await page.getByRole('button',{name:'刷新验收状态'}).click();await page.getByText(acceptance.reason,{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'确认服务完成',exact:true}).isVisible(),false);
mode='unauth';await page.goto(origin+'/screens/settlement-statements.html');await page.getByText('登录后查看结算与对账',{exact:true}).waitFor();assert.equal(await page.locator('table').count(),0);assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks:['authorized-scope','unauthenticated-empty','bigint-money','xss-escaping','adjustment-preview-submit','auto-policy-disabled-nodes','approval-revision','external-evidence-id','csv-xlsx-pdf-download','mobile-no-overflow','configuration-create-and-independent-approval','customer-acceptance-server-eligibility','acceptance-script-references','utc-sql-date-to-business-period','profile-collection-contract-separation','own-funds-explicit-capability-and-independent-approval','compensation-original-unit-independent-source','recovery-payment-progress','policy-disable-confirmation','directional-commission-metrics','dispute-evidence-required'],requests:posts.length,screenshots:['/tmp/settlement-admin-desktop.png','/tmp/settlement-statement-desktop.png','/tmp/settlement-statements-mobile.png']}));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
